# Generated by Django 4.1.6 on 2023-02-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='depatments',
            field=models.CharField(choices=[('Developer', 'Developer'), ('CTO', 'CTO'), ('Admin', 'Admin'), ('HR', 'HR')], max_length=10),
        ),
    ]
