# Generated by Django 4.1.6 on 2023-02-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='name',
            field=models.CharField(choices=[('1', 'HR'), ('4', 'CTO'), ('2', 'Developer'), ('3', 'Admin')], default='HR', max_length=20),
        ),
    ]
