# Generated by Django 4.1.6 on 2023-02-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_depatment_select_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='select_role',
            field=models.CharField(choices=[('HR', 'HR'), ('DEVELOPER', 'Developer'), ('ADMIN', 'Admin'), ('CTO', 'CTO')], default='HR', max_length=20),
        ),
    ]
