# Generated by Django 4.1.6 on 2023-02-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_depatment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='depatment',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR'), ('DEVLOPER', 'Developer'), ('CTO', 'CTO')], default='HR', max_length=20),
        ),
    ]
