# Generated by Django 4.1.6 on 2023-02-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='depatments',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Admin', 'Admin'), ('HR', 'HR'), ('CTO', 'CTO')], max_length=10),
        ),
    ]
