# Generated by Django 4.1.6 on 2023-02-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_depatments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='depatments',
            field=models.CharField(choices=[('Admin', 'Admin'), ('CTO', 'CTO'), ('HR', 'HR'), ('Developer', 'Developer')], max_length=10),
        ),
    ]
