# Generated by Django 4.1.6 on 2023-02-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_depatment_select_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='select_role',
            field=models.CharField(choices=[('HR', 'HR'), ('CTO', 'CTO'), ('ADMIN', 'Admin'), ('DEVELOPER', 'Developer')], default='HR', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
