# Generated by Django 4.1.6 on 2023-02-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depatments', models.CharField(choices=[('Admin', 'Admin'), ('CTO', 'CTO'), ('HR', 'HR'), ('Developer', 'Developer')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='depatments',
        ),
        migrations.AddField(
            model_name='employee',
            name='depatments',
            field=models.ManyToManyField(to='employee.depatment'),
        ),
    ]
