# Generated by Django 4.1.6 on 2023-02-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_depatment_remove_employee_depatments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='depatments',
            field=models.CharField(choices=[('HR', 'HR'), ('CTO', 'CTO'), ('Admin', 'Admin'), ('Developer', 'Developer')], max_length=100),
        ),
    ]
