# Generated by Django 4.1.6 on 2023-02-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_depatment_depatments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='depatments',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Developer', 'Developer'), ('HR', 'HR'), ('CTO', 'CTO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
