# Generated by Django 4.1.6 on 2023-02-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_depatment_depatments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='depatments',
            field=models.CharField(choices=[('CTO', 'CTO'), ('Developer', 'Developer'), ('HR', 'HR'), ('Admin', 'Admin')], max_length=100),
        ),
    ]
