# Generated by Django 4.1.6 on 2023-02-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_depatment_depatments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='depatments',
            field=models.CharField(choices=[('Developer', 'Developer'), ('CTO', 'CTO'), ('Admin', 'Admin'), ('HR', 'HR')], max_length=100),
        ),
    ]
