# Generated by Django 4.1.6 on 2023-02-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_depatment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CTO', 'CTO'), ('HR', 'HR'), ('DEVLOPER', 'Developer')], default='HR', max_length=20),
        ),
    ]
