# Generated by Django 4.1.6 on 2023-02-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_depatment_depatments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
        migrations.AlterField(
            model_name='depatment',
            name='depatments',
            field=models.CharField(choices=[('CTO', 'CTO'), ('HR', 'HR'), ('Developer', 'Developer'), ('Admin', 'Admin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
