# Generated by Django 4.1.6 on 2023-02-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_depatment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='name',
            field=models.CharField(choices=[('CTO', 'CTO'), ('DEVLOPER', 'Developer'), ('ADMIN', 'Admin'), ('HR', 'HR')], default='HR', max_length=20),
        ),
    ]
