# Generated by Django 4.1.6 on 2023-02-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_remove_employee_username_alter_depatment_depatments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='depatment',
            name='depatments',
            field=models.CharField(choices=[('HR', 'HR'), ('CTO', 'CTO'), ('Developer', 'Developer'), ('Admin', 'Admin')], max_length=100),
        ),
    ]
