# Generated by Django 4.1.6 on 2023-02-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_alter_depatment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='name',
            field=models.CharField(choices=[('HR', 'HR'), ('CTO', 'CTO'), ('DEVLOPER', 'Developer'), ('ADMIN', 'Admin')], default='HR', max_length=20),
        ),
    ]
