# Generated by Django 4.1.6 on 2023-02-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_depatment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='name',
            field=models.CharField(choices=[('DEVLOPER', 'Developer'), ('CTO', 'CTO'), ('HR', 'HR'), ('ADMIN', 'Admin')], default='HR', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
