# Generated by Django 4.1.6 on 2023-02-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_alter_depatment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR'), ('DEVELOPER', 'Developer'), ('CTO', 'CTO')], default='HR', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
