# Generated by Django 4.1.6 on 2023-02-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_alter_depatment_name_alter_employee_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='name',
            field=models.CharField(choices=[('CTO', 'CTO'), ('DEVELOPER', 'Developer'), ('ADMIN', 'Admin'), ('HR', 'HR')], default='HR', max_length=20),
        ),
    ]
