# Generated by Django 4.1.6 on 2023-02-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_alter_depatment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='name',
            field=models.CharField(choices=[('HR', 'HR'), ('ADMIN', 'Admin'), ('DEVELOPER', 'Developer'), ('CTO', 'CTO')], default='HR', max_length=20),
        ),
    ]
