# Generated by Django 4.1.6 on 2023-02-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_alter_depatment_depatments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depatment',
            name='depatments',
            field=models.CharField(choices=[('HR', 'HR'), ('Admin', 'Admin'), ('Developer', 'Developer'), ('CTO', 'CTO')], max_length=100),
        ),
    ]
